FROM node:12-alpine3.10

WORKDIR /usr/src/app

COPY package*.json ./

RUN npm i npm@latest -g

RUN npm install

RUN npm install -g @angular/cli 

COPY . .

RUN ng build --prod --configuration production
